### ISSUE TITLE
Can't use aarch64 jdk14 as bootstrap jdk

### ISSUE THREAD

**Issue by navyxliu** [AdoptOpenJDK/openjdk14-binaries#1]
I got this binary from AdoptOpenJDK website and plan to use it as bootjdk. 
OpenJDK14U-jdk_aarch64_linux_hotspot_14.0.1_7.tar.gz

```
$~/builds/jdk-14.0.1+7$ ./bin/java -version
[0.008s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 65536 actual: 4096
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode)
```
I got an error message of [cds]. It's very that error message prevents openjdk's configure script from determining bootjdk version.

I posted the question here and yes I also suspected your build openjdk14 with 64k page. 
http://openjdk.5641.n7.nabble.com/FW-Mach5-mach5-one-phh-JDK-8151779-20200427-2151-10554367-FAILED-tp409003p409006.html

**Comment by theRealAph** [comment]
It would be very useful to make the configure script robust against warnings.

**Comment by navyxliu** [comment]
Andrew, 

Thanks. 
I've file an issue for this: https://bugs.openjdk.java.net/browse/JDK-8244248
close it because it has been solved.
